# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sequoia < Formula
  desc "Multi-agent code audit framework with Go CLI installer and TUI.
Deploy specialized AI agents to inspect projects from every angle
in parallel.
"
  homepage "https://github.com/Crisbr10/sequoia"
  version "1.0.29"
  license "MIT"

  on_macos do
    url "https://github.com/Crisbr10/sequoia/releases/download/v1.0.29/sequoia_1.0.29_darwin_all.tar.gz"
    sha256 "a8944b2bb8685a912afb4f740420a7ccf8a691c52e79ba8ed2b08ded378bea02"

    define_method(:install) do
      bin.install "sequoia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Crisbr10/sequoia/releases/download/v1.0.29/sequoia_1.0.29_linux_amd64.tar.gz"
      sha256 "2436d41019dcf15408e43be51e310a57e3853cadba1e6b24705913bbce267bf3"
      define_method(:install) do
        bin.install "sequoia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Crisbr10/sequoia/releases/download/v1.0.29/sequoia_1.0.29_linux_arm64.tar.gz"
      sha256 "a38f40dfe378f0638dca84cf5007f2ed9e61418498944a8b83780c31b98ed4a6"
      define_method(:install) do
        bin.install "sequoia"
      end
    end
  end
end
