# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sequoia < Formula
  desc "Multi-agent code audit framework with Go CLI installer and TUI.
Deploy specialized AI agents to inspect projects from every angle
in parallel.
"
  homepage "https://github.com/Crisbr10/sequoia"
  version "1.0.3"
  license "MIT"

  on_macos do
    url "https://github.com/Crisbr10/sequoia/releases/download/v1.0.3/sequoia_1.0.3_darwin_all.tar.gz"
    sha256 "c8f7b1bc5553ef60b74718eacf891397d5096216460a1620205981fe0852b838"

    define_method(:install) do
      bin.install "sequoia"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Crisbr10/sequoia/releases/download/v1.0.3/sequoia_1.0.3_linux_amd64.tar.gz"
      sha256 "805d0ce642775bd00f0d554065faa953bd2c1898a3806d7342886712657554be"
      define_method(:install) do
        bin.install "sequoia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Crisbr10/sequoia/releases/download/v1.0.3/sequoia_1.0.3_linux_arm64.tar.gz"
      sha256 "a043db23cca1c69f2785fbb3d23d01faf7f7a9c12ed71f34a88e35b30068cc7d"
      define_method(:install) do
        bin.install "sequoia"
      end
    end
  end
end
